
import { Area, StudyStatus } from './types';

export interface HotTopic {
  name: string;
  area: string;
  category: 'Clínica Médica' | 'Cirurgia Geral' | 'Ginecologia e Obstetrícia' | 'Pediatria' | 'Medicina Preventiva';
}

export const HOT_TOPICS_LIST: HotTopic[] = [
  // CLÍNICA MÉDICA (PÁG 1)
  { name: "Hipertensão arterial", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Insuficiência cardíaca", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Infarto agudo do miocárdio", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Cefaleia", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Terapia antitrombótica – CHA2DS2 – VASc", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Doenças da placa (miastenia, eaton lambert)", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Tireoide (hiper/hipo/nódulos)", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Artrites e espondilites", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Obesidade", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Malária", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Diabetes Mellitus", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Mecanismo medicamentoso (furosemida)", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Hemorragia digestiva alta", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Asma", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Cirrose alcoólica descompensada", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Glomerulopatias", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Síndrome da fragilidade no idoso – Fried", area: "Geriatria", category: 'Clínica Médica' },
  { name: "Lúpus eritematoso sistêmico", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Transfusão de hemocomponentes", area: "Hematologia", category: 'Clínica Médica' },
  { name: "DPOC (vacinas, manejo)", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "HIV – AIDSs – doenças oportunistas", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Tuberculose", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Sepse", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Trombopatias (trombofilia, trombocitemia)", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Intoxicação metanol", area: "Emergência", category: 'Clínica Médica' },
  { name: "Leucemias mieloide e linfocítica", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Nefrolitíase", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Neutropenia febril e síndrome da lise tumoral", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Lesão renal aguda", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Hepatites", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Hemorragia subaracnoidea", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Doença inflamatória intestinal", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Epilepsia", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Febre reumática", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "AVC", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Endocardite – critérios de Duke", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Psiquiatria (ideação suicida, delírio)", area: "Psiquiatria", category: 'Clínica Médica' },
  { name: "Síndrome do choque tóxico", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Efeitos adversos - haloperidol", area: "Psiquiatria", category: 'Clínica Médica' },
  { name: "Choques (cardiogênico, hipovolêmico, misto, neurogênico)", area: "Emergência", category: 'Clínica Médica' },
  { name: "Hanseníase", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Esclerose sistêmica", area: "Reumatologia", category: 'Clínica Médica' },
  { name: "Neuropatias (ELA, Guillain Barre, esclerose múltipla)", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Lombalgia - radiculopatias", area: "Neurologia", category: 'Clínica Médica' },
  { name: "Nódulos hepáticos", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Esteatose hepática", area: "Hepatologia", category: 'Clínica Médica' },
  { name: "Disfagia aguda (DRGE, acalásia, esofagite)", area: "Gastroenterologia", category: 'Clínica Médica' },
  { name: "Hemofilias", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Anemias", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Dengue e arboviroses", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Esporotricose e escabiose", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Leishmaniose", area: "Infectologia", category: 'Clínica Médica' },
  { name: "Pneumonia", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Doenças hipofisárias", area: "Endocrinologia", category: 'Clínica Médica' },
  { name: "Análise de líquidos (pleural, ascítico)", area: "Pneumologia", category: 'Clínica Médica' },
  { name: "Linfomas", area: "Hematologia", category: 'Clínica Médica' },
  { name: "Fibrilação atrial", area: "Cardiologia", category: 'Clínica Médica' },
  { name: "Doença renal crônica", area: "Nefrologia", category: 'Clínica Médica' },
  { name: "Distúrbios hidroeletrolíticos e ECG", area: "Nefrologia", category: 'Clínica Médica' },

  // CIRURGIA GERAL (PÁG 2)
  { name: "Apendicite aguda", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Nefrolitíase", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Diverticulite e diverticulose", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Abdome agudo em crianças", area: "Cirurgia Pediátrica", category: 'Cirurgia Geral' },
  { name: "Colelitíase, colecistite, colangite", area: "Vias Biliares", category: 'Cirurgia Geral' },
  { name: "Nódulos hepáticos", area: "Hepatobiliar", category: 'Cirurgia Geral' },
  { name: "Hemorragia digestiva alta", area: "Geral", category: 'Cirurgia Geral' },
  { name: "CA de próstata", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Hemorragia digestiva baixa", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Drenagem e análise líquido pleural", area: "Técnica", category: 'Cirurgia Geral' },
  { name: "Pancreatite aguda e crônica", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Profilaxia TEV", area: "Pré-operatório", category: 'Cirurgia Geral' },
  { name: "Hérnias", area: "Parede Abdominal", category: 'Cirurgia Geral' },
  { name: "Cisto tireoglosso e cervical", area: "Cabeça e Pescoço", category: 'Cirurgia Geral' },
  { name: "Doenças orificiais", area: "Proctologia", category: 'Cirurgia Geral' },
  { name: "DRGE", area: "Gastro / Geral", category: 'Cirurgia Geral' },
  { name: "Torção ovariana", area: "Urgência", category: 'Cirurgia Geral' },
  { name: "Tamponameto cardíaco", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "ATLS", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "Resposta metabólica ao trauma", area: "REMIT", category: 'Cirurgia Geral' },
  { name: "Abdome agudo obstrutivo", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Procedimentos (AVC, cantoplastia, drenagem)", area: "Técnica", category: 'Cirurgia Geral' },
  { name: "Grandes queimados", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "Tumor cabeça de pâncreas e vias biliares", area: "Oncologia", category: 'Cirurgia Geral' },
  { name: "Abdome agudo isquêmico", area: "Abdome Agudo", category: 'Cirurgia Geral' },
  { name: "Doença inflamatória intestinal", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Úlceras de pressão", area: "Geral", category: 'Cirurgia Geral' },
  { name: "Trombose venose profunda e úlceras", area: "Vascular", category: 'Cirurgia Geral' },
  { name: "Pneumotórax, hemotórax", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "Urgência urológicas", area: "Urologia", category: 'Cirurgia Geral' },
  { name: "Protocolo transfusão maciça", area: "Trauma", category: 'Cirurgia Geral' },
  { name: "CA de esôfago, estômago, cólon", area: "Oncologia", category: 'Cirurgia Geral' },

  // GINECOLOGIA E OBSTETRÍCIA (PÁG 3)
  { name: "Anticoncepção", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Miomatose uterina", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Ciclo menstrual", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Manejo vítima violência sexual", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Hiperplasia e atrofia endometrial", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Úlceras genitais", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento uterino anormal", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "ISTs: HIV, sífilis, herpes", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Corrimentos vaginais", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Endometriose", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Pólipos endometriais", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "CA mama – BI RADS", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Seguimento gestante e ISTs", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Análise de Doppler", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Toxoplasmose gestacional", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Aloimunização", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sífilis na gestação", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Hemorragia pós - parto", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Alterações no líquido amniótico", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Gestante com tuberculose, malária, dengue", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sinais gravidez", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "HPV", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Doença hipertensiva da gestação", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Hiperêmese gravídica", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Diabetes gestacional", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Pré – natal", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento de 1º trimestre", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Doença trofoblástica gestacional", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Sangramento de 2º trimestre", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Gravidez gemelar", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Gravidez ectópica", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Trabalho de parto – fases e períodos", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Partograma", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Abdome agudo obstétrico/ginecológico", area: "Urgência", category: 'Ginecologia e Obstetrícia' },
  { name: "Distócias", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Embriogênese", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Menopausa", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Amenorreias - hipogonadismo", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Endometrite", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Colo curto e parto prematuro", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Cardiotocografia", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Rastreio CA de útero – DNA HPV", area: "Ginecologia", category: 'Ginecologia e Obstetrícia' },
  { name: "Drogas usadas X não usadas na gestação", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Maturação cervical – Bishop", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },
  { name: "Aplicabilidade do fórceps", area: "Obstetrícia", category: 'Ginecologia e Obstetrícia' },

  // PEDIATRIA (PÁG 4)
  { name: "Obstrução intestinal", area: "Cirurgia Pediátrica", category: 'Pediatria' },
  { name: "Psiquiatria infantil – autismo e TDAH", area: "Psiquiatria", category: 'Pediatria' },
  { name: "Toxoplasmose congênita", area: "Neonatologia", category: 'Pediatria' },
  { name: "Púrpura trombocitopênica idiopática", area: "Hematologia", category: 'Pediatria' },
  { name: "Sífilis congênita", area: "Neonatologia", category: 'Pediatria' },
  { name: "Asma", area: "Pneumologia", category: 'Pediatria' },
  { name: "Glomerulonefrites na infância", area: "Nefrologia", category: 'Pediatria' },
  { name: "Diabetes tipo 1 – cetoacidose", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Calendário vacinal", area: "Puericultura", category: 'Pediatria' },
  { name: "Diarreia e manejo da desidratação", area: "Infectologia", category: 'Pediatria' },
  { name: "Leucemias mielódes e linfocíticas", area: "Hematologia", category: 'Pediatria' },
  { name: "Doença de Kawasaki", area: "Reumatologia", category: 'Pediatria' },
  { name: "Doenças exantemáticas", area: "Infectologia", category: 'Pediatria' },
  { name: "Anemia de Falconi", area: "Hematologia", category: 'Pediatria' },
  { name: "Reanimação neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Maus trattos – síndr do bebê sacudido", area: "Social", category: 'Pediatria' },
  { name: "Classificações do RN (peso, IG)", area: "Neonatologia", category: 'Pediatria' },
  { name: "Icterícia neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Hemofilias", area: "Hematologia", category: 'Pediatria' },
  { name: "Rinossinusite", area: "Otorrino", category: 'Pediatria' },
  { name: "Artrites", area: "Reumatologia", category: 'Pediatria' },
  { name: "Hipovitaminoses", area: "Nutrologia", category: 'Pediatria' },
  { name: "Febre reumática", area: "Reumatologia", category: 'Pediatria' },
  { name: "Má formações da parede abdominal", area: "Cirurgia Pediátrica", category: 'Pediatria' },
  { name: "Testes de triagem neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "Anemias – ferropriva, megaloblástica", area: "Hematologia", category: 'Pediatria' },
  { name: "Doenças do teste do pézinho", area: "Neonatologia", category: 'Pediatria' },
  { name: "Galactosemia", area: "Genética", category: 'Pediatria' },
  { name: "Anafilazia", area: "Alergia", category: 'Pediatria' },
  { name: "Investigação baixa estatura", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Aleitamento materno", area: "Puericultura", category: 'Pediatria' },
  { name: "Mononucleose infecciosa", area: "Infectologia", category: 'Pediatria' },
  { name: "Malária na criança", area: "Infectologia", category: 'Pediatria' },
  { name: "Desenvolvimento sexual - puberdade", area: "Endocrinologia", category: 'Pediatria' },
  { name: "Mastite fúngica", area: "Puericultura", category: 'Pediatria' },
  { name: "Hipoglicemia neonatal", area: "Neonatologia", category: 'Pediatria' },
  { name: "RN exposto ao HIV", area: "Infectologia", category: 'Pediatria' },
  { name: "Laringocele / Laringomalácea", area: "Otorrino", category: 'Pediatria' },
  { name: "Síndromes respiratórias do RN", area: "Neonatologia", category: 'Pediatria' },
  { name: "BLS / ATLS na criança", area: "Emergência", category: 'Pediatria' },
  { name: "Sobrepeso e obesidade", area: "Nutrologia", category: 'Pediatria' },
  { name: "Síndromes: Prader Willi, Turner, Down, Noonan", area: "Genética", category: 'Pediatria' },
  { name: "Fibrose cística", area: "Pneumologia", category: 'Pediatria' },
  { name: "Verminoses e associações", area: "Infectologia", category: 'Pediatria' },
  { name: "Paralisia obstétrica plexo braquial", area: "Neonatologia", category: 'Pediatria' },
  { name: "Cardiopatias congênitas", area: "Cardiologia", category: 'Pediatria' },
  { name: "Bebê sibilante", area: "Pneumologia", category: 'Pediatria' },
  { name: "Interssupção intestinal", area: "Cirurgia Pediátrica", category: 'Pediatria' },
  { name: "Corpo estranho – estridor", area: "Emergência", category: 'Pediatria' },
  { name: "Leishmaniose", area: "Infectologia", category: 'Pediatria' },
  { name: "Neuroblastoma e nefroblastoma", area: "Oncologia", category: 'Pediatria' },
  { name: "Urgências urológicas", area: "Urologia", category: 'Pediatria' },
  { name: "Paralisia de Erb - Duchenne", area: "Neonatologia", category: 'Pediatria' },
  { name: "Celulite pré/pós septal", area: "Infectologia", category: 'Pediatria' },
  { name: "Marcos do neurodesenvolvimento", area: "Puericultura", category: 'Pediatria' },
  { name: "Catarata e glaucoma congênito", area: "Oftalmologia", category: 'Pediatria' },

  // PREVENTIVA (PÁG 5)
  { name: "Níveis de prevenção em saúde", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Atenção domiciliar", area: "Gestão", category: 'Medicina Preventiva' },
  { name: "Atributos da atenção primária", area: "APS", category: 'Medicina Preventiva' },
  { name: "Princípios do SUS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Protocolo SPIKES", area: "Comunicação", category: 'Medicina Preventiva' },
  { name: "Leis orgânicas: 8.080 e 8.142", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Rastreamentos: CA útero, mama, próstata", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Doenças de notificação imediata", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "MCCP: método clínico centrado na pessa", area: "Comunicação", category: 'Medicina Preventiva' },
  { name: "Sinais de prontidão – introdução alimentar", area: "APS / Nutrição", category: 'Medicina Preventiva' },
  { name: "Princípios da atenção primária", area: "APS", category: 'Medicina Preventiva' },
  { name: "Tuberculose latente – investigação e tratamento", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Testes de rastreamento populacional", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Estudos epidemmiológicos", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "População indígena e ribeirinha", area: "Saúde Coletiva", category: 'Medicina Preventiva' },
  { name: "Instrumentos de abordagem familiar", area: "APS", category: 'Medicina Preventiva' },
  { name: "Calendário vacinal", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Razão de verossimilhança (likehood ratio)", area: "Epidemio Clínica", category: 'Medicina Preventiva' },
  { name: "Atenção psicossocial", area: "Saúde Mental", category: 'Medicina Preventiva' },
  { name: "Consultas de pré - natal", area: "APS / GO", category: 'Medicina Preventiva' },
  { name: "Vertigem na APS: VPPB, ménière, neurite", area: "APS / Otorrino", category: 'Medicina Preventiva' },
  { name: "Atribuições de membros da equipe da APS", area: "Gestão", category: 'Medicina Preventiva' },
  { name: "Número necessário a tratar", area: "Epidemio Clínica", category: 'Medicina Preventiva' },
  { name: "Participação social no SUS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "HIV: profilaxias", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Critérios insulinoterapia", area: "Endocrinologia", category: 'Medicina Preventiva' },
  { name: "Desprescrição", area: "APS / Geriatria", category: 'Medicina Preventiva' },
  { name: "Fases do ciclo de vida familiar", area: "APS", category: 'Medicina Preventiva' },
  { name: "SOAP", area: "APS", category: 'Medicina Preventiva' },
  { name: "Atestado de óbito", area: "Ética e Legal", category: 'Medicina Preventiva' },
  { name: "Cálculos – tabela 2X2", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Cuidados paliativos", area: "Geral", category: 'Medicina Preventiva' },
  { name: "Composição ESF – unidades territoriais", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Escabiose", area: "Dermatologia", category: 'Medicina Preventiva' },
  { name: "Financiamento da APS", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Dengue", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Risco relativo e risco absoluto", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "Estágio motivacionais de Prochaska e Diclem.", area: "Psicologia", category: 'Medicina Preventiva' },
  { name: "Polifarmácia", area: "APS / Geriatria", category: 'Medicina Preventiva' },
  { name: "Seguimento de sífilis na APS", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "PNAB", area: "SUS", category: 'Medicina Preventiva' },
  { name: "Atendimento vítimas de violência sexual", area: "Saúde Coletiva", category: 'Medicina Preventiva' },
  { name: "Cuidado e seguimento do idoso na APS", area: "APS", category: 'Medicina Preventiva' },
  { name: "Modelos Flexneriano X Dawnosiano", area: "História Med", category: 'Medicina Preventiva' },
  { name: "Valor preditivo positivo e negativo", area: "Epidemiologia", category: 'Medicina Preventiva' },
  { name: "ITU na gestante", area: "APS / GO", category: 'Medicina Preventiva' },
  { name: "Testes de tuberculose", area: "Vigilância", category: 'Medicina Preventiva' },
  { name: "Programas de rastreio na APS", area: "Gestão", category: 'Medicina Preventiva' }
];

export const CURRICULUM_DATA: Area[] = [
  {
    id: 'clinica-medica',
    name: 'Clínica Médica',
    icon: '🩺',
    color: 'blue',
    topics: [
      { id: 'cm-1', name: 'Hipertensão arterial', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-2', name: 'Insuficiência cardíaca', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-3', name: 'Infarto agudo do miocárdio', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-4', name: 'Fibrilação atrial', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-5', name: 'Terapia antitrombótica – CHA2DS2 – VASc', subArea: 'Cardiologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-6', name: 'Distúrbios hidroeletrolíticos e ECG', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-7', name: 'Nefrolitíase', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-8', name: 'Lesão renal aguda', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-9', name: 'Doença renal crônica', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-10', name: 'Glomerulopatias', subArea: 'Nefrologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-11', name: 'Tireoide (hiper/hipo/nódulos)', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-12', name: 'Diabetes Mellitus', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-13', name: 'Obesidade', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-14', name: 'Doenças hipofisárias', subArea: 'Endocrinologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-15', name: 'Hemorragia digestiva alta', subArea: 'Gastroenterologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-16', name: 'Cirrose alcoólica descompensada', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-17', name: 'Hepatites', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-18', name: 'Nódulos hepáticos e Esteatose hepática', subArea: 'Hepatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-19', name: 'HIV – AIDSs – doenças oportunistas', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-20', name: 'Sepse', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-21', name: 'Febre reumática e Endocardite (Duke)', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-22', name: 'Dengue, arboviroses e Malária', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-23', name: 'Hanseníase e Leishmaniose', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-24', name: 'Artrites e espondilites', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-25', name: 'Lúpus eritematoso sistêmico', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-26', name: 'Esclerose sistêmica', subArea: 'Reumatologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-27', name: 'Anemias, Hemofilias e Linfomas', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-28', name: 'Leucemias mieloide e linfocítica', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-29', name: 'AVC e Hemorragia subaracnoidea', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-30', name: 'Epilepsia e Cefaleia', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-31', name: 'Neuropatias (ELA, Guillain Barre, EM)', subArea: 'Neurologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-32', name: 'Asma, DPOC e Tuberculose', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-33', name: 'Pneumonia e Análise de líquidos', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'cm-34', name: 'Síndrome da fragilidade no idoso – Fried', subArea: 'Geriatria', status: StudyStatus.NOT_STARTED },
      { id: 'cm-35', name: 'Psiquiatria (ideação suicida, delírio)', subArea: 'Psiquiatria', status: StudyStatus.NOT_STARTED },
      { id: 'cm-36', name: 'Efeitos adversos - haloperidol', subArea: 'Psiquiatria', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'cirurgica',
    name: 'Cirurgia Geral',
    icon: '🔪',
    color: 'red',
    topics: [
      { id: 'cg-1', name: 'Apendicite aguda', subArea: 'Abdome Agudo', status: StudyStatus.NOT_STARTED },
      { id: 'cg-2', name: 'Diverticulite e diverticulose', subArea: 'Abdome Agudo', status: StudyStatus.NOT_STARTED },
      { id: 'cg-3', name: 'Colelitíase, colecistite, colangite', subArea: 'Vias Biliares', status: StudyStatus.NOT_STARTED },
      { id: 'cg-4', name: 'Pancreatite aguda e crônica', subArea: 'Abdome Agudo', status: StudyStatus.NOT_STARTED },
      { id: 'cg-5', name: 'Hemorragia digestiva alta e baixa', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cg-6', name: 'ATLS e Resposta metabólica ao trauma', subArea: 'Trauma', status: StudyStatus.NOT_STARTED },
      { id: 'cg-7', name: 'Abdome agudo obstrutivo e isquêmico', subArea: 'Abdome Agudo', status: StudyStatus.NOT_STARTED },
      { id: 'cg-8', name: 'Hérnias e Doenças orificiais', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cg-9', name: 'Grandes queimados', subArea: 'Trauma', status: StudyStatus.NOT_STARTED },
      { id: 'cg-10', name: 'Pneumotórax e hemotórax', subArea: 'Trauma', status: StudyStatus.NOT_STARTED },
      { id: 'cg-11', name: 'CA de esôfago, estômago, cólon', subArea: 'Oncologia', status: StudyStatus.NOT_STARTED },
      { id: 'cg-12', name: 'Tumor cabeça de pâncreas e vias biliares', subArea: 'Oncologia', status: StudyStatus.NOT_STARTED },
      { id: 'cg-13', name: 'CA de próstata e Urgência urológicas', subArea: 'Urologia', status: StudyStatus.NOT_STARTED },
      { id: 'cg-14', name: 'Nefrolitíase (Cirurgia)', subArea: 'Urologia', status: StudyStatus.NOT_STARTED },
      { id: 'cg-15', name: 'Protocolo transfusão maciça', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cg-16', name: 'Drenagem e análise líquido pleural', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'cg-17', name: 'DRGE e Abdome agudo em crianças', subArea: 'Especialidades', status: StudyStatus.NOT_STARTED },
      { id: 'cg-18', name: 'Tamponamento cardíaco', subArea: 'Trauma/Emergência', status: StudyStatus.NOT_STARTED },
      { id: 'cg-19', name: 'Procedimentos (AVC, cantoplastia, drenagem)', subArea: 'Técnica', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'go',
    name: 'Ginecologia e Obstetrícia',
    icon: '🤰',
    color: 'pink',
    topics: [
      { id: 'go-1', name: 'Anticoncepção e Ciclo menstrual', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-2', name: 'Sangramento uterino anormal e Endometriose', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-3', name: 'Corrimentos vaginais e ISTs (HIV, Sífilis)', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-4', name: 'CA mama (BI-RADS) e Miomatose uterina', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-5', name: 'Amenorreias e Hipogonadismo', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-6', name: 'Manejo vítima violência sexual', subArea: 'Ginecologia', status: StudyStatus.NOT_STARTED },
      { id: 'go-7', name: 'Doença hipertensiva da gestação', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-8', name: 'Diabetes gestacional', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-9', name: 'Sangramento 1º e 2º trimestres', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-10', name: 'Gravidez ectópica e Gemelaridade', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-11', name: 'Pré-natal e Sinais de gravidez', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-12', name: 'Trabalho de parto: fases e períodos', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-13', name: 'Partograma e Distócias', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-14', name: 'Hemorragia pós-parto', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-15', name: 'Toxoplasmose e Sífilis na gestação', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-16', name: 'Aloimunização e Cardiotocografia', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-17', name: 'Colo curto e parto prematuro', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
      { id: 'go-18', name: 'Maturação cervical – Bishop', subArea: 'Obstetrícia', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'pediatria',
    name: 'Pediatria',
    icon: '👶',
    color: 'green',
    topics: [
      { id: 'pd-1', name: 'Neonatologia: Reanimação e Classificações', subArea: 'Neonatologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-2', name: 'Icterícia neonatal e Hipoglicemia', subArea: 'Neonatologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-3', name: 'Calendário vacinal e Imunização', subArea: 'Puericultura', status: StudyStatus.NOT_STARTED },
      { id: 'pd-4', name: 'Aleitamento materno', subArea: 'Puericultura', status: StudyStatus.NOT_STARTED },
      { id: 'pd-5', name: 'Desenvolvimento e marcos do neurodesenvolvimento', subArea: 'Puericultura', status: StudyStatus.NOT_STARTED },
      { id: 'pd-6', name: 'Diarreia e manejo da desidratação', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-7', name: 'Doenças exantemáticas', subArea: 'Infectologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-8', name: 'Síndromes respiratórias e Bebê sibilante', subArea: 'Pneumologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-9', name: 'Asma e Diabetes tipo 1 (CAD)', subArea: 'Geral', status: StudyStatus.NOT_STARTED },
      { id: 'pd-10', name: 'Anemias (Ferropriva e Megaloblástica)', subArea: 'Hematologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-11', name: 'Leucemias e Neuroblastoma', subArea: 'Oncologia', status: StudyStatus.NOT_STARTED },
      { id: 'pd-12', name: 'Obstrução intestinal (Invaginação/Atresias)', subArea: 'Cirurgia Pediátrica', status: StudyStatus.NOT_STARTED },
      { id: 'pd-13', name: 'Maus tratos – Síndr. bebê sacudido', subArea: 'Social', status: StudyStatus.NOT_STARTED },
      { id: 'pd-14', name: 'Psiquiatria infantil – Autismo e TDAH', subArea: 'Psiquiatria', status: StudyStatus.NOT_STARTED },
    ]
  },
  {
    id: 'preventiva',
    name: 'Medicina Preventiva e Social',
    icon: '🏥',
    color: 'indigo',
    topics: [
      { id: 'pv-1', name: 'Princípios do SUS e Leis Orgânicas (8080/8142)', subArea: 'SUS', status: StudyStatus.NOT_STARTED },
      { id: 'pv-2', name: 'Atributos e Princípios da Atenção Primária', subArea: 'APS', status: StudyStatus.NOT_STARTED },
      { id: 'pv-3', name: 'PNAB e Composição ESF', subArea: 'APS', status: StudyStatus.NOT_STARTED },
      { id: 'pv-4', name: 'Níveis de prevenção em saúde', subArea: 'Epidemiologia', status: StudyStatus.NOT_STARTED },
      { id: 'pv-5', name: 'Estudos epidemiológicos e Cálculos 2x2', subArea: 'Epidemiologia', status: StudyStatus.NOT_STARTED },
      { id: 'pv-6', name: 'Risco relativo e risco absoluto', subArea: 'Epidemiologia', status: StudyStatus.NOT_STARTED },
      { id: 'pv-7', name: 'Valor preditivo (+/-) e Sensibilidade/Especificidade', subArea: 'Epidemiologia', status: StudyStatus.NOT_STARTED },
      { id: 'pv-8', name: 'Doenças de notificação imediata', subArea: 'Vigilância', status: StudyStatus.NOT_STARTED },
      { id: 'pv-9', name: 'Rastreios (CA útero, mama, próstata)', subArea: 'Prevenção', status: StudyStatus.NOT_STARTED },
      { id: 'pv-10', name: 'Protocolo SPIKES e MCCP', subArea: 'Comunicação', status: StudyStatus.NOT_STARTED },
      { id: 'pv-11', name: 'Atestado de óbito e Cuidados paliativos', subArea: 'Ética/Social', status: StudyStatus.NOT_STARTED },
      { id: 'pv-12', name: 'Financiamento do APS', subArea: 'Gestão', status: StudyStatus.NOT_STARTED },
    ]
  }
];
